export const SELECT_CLIENT = 'SELECT_CLIENT';
export const CLEAR_LOCAL_HISTORY = 'CLEAR_LOCAL_HISTORY';
export const CLEAR_SELECT_CLIENT = 'CLEAR_SELECT_CLIENT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const SELECT_MANAGER = 'SELECT_MANAGER';
export const IF_CAN_ADD_OPPORTUNITY = 'IF_CAN_ADD_OPPORTUNITY';
export const INIT_CLIENT = 'INIT_CLIENT';
